### ISSUE TITLE
Error page if request more than 5 print job per day

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#10]
**This card should use the general error page component from the other card**
Each person (determined by email) is only allowed to request one 3D print job per day. Create an error page if a user requests more than 5 job in a given day that explains the situation and directs them to speak with a staff member.

- [ ] Done after Submission form 
- [ ] Check for error in request
- [ ] Use error notification component to display the error that they submitted more than 5

**Comment by duyquangnguyenhac** [comment]
Can I claim this issue ?, James

**Comment by duyquangnguyenhac** [comment]
hi, has anyone claimed this issue ? Could I take a shot at it ?

**Comment by dviramontes** [comment]
@duyquangnguyenhac go for it :)

**Comment by duyquangnguyenhac** [comment]
Could you assign it to me, sorry for the late reply.
Thank you, James

**Comment by hannahkamundson** [comment]
@duyquangnguyenhac You still interested?

**Comment by duyquangnguyenhac** [comment]
Yes! Sorry! I'm still interested and I'm working on it at this moment.
- James

**Comment by duyquangnguyenhac** [comment]
Hi, is there a discord server I could join? I can't seem to find the username and password to login to ideaLab. I tried the usernames and passwords in `import.sql` but it didn't work. The discord link in the presentation doesn't work. What link should I use?
Thank you.

**Comment by duyquangnguyenhac** [comment]
Hi, Can someone please get back to my comment above, thank you.
