### ISSUE TITLE
updated_at, created_at columns should be added to db tables.

### ISSUE THREAD

**Issue by kaansonmezoz** [codefordenver/ideaLab#129]
- updated_at column should be added to tables. This way we can track when the record modification has happened. Data type: DateTime
- created_at column should be added to tables. Thanks to this, we can track when the record has been created.
- When record is updated, don't forget to update the updated_at
- When record is created, updated_at == created_at
- Don't forget to update the model classes in java project !

**Comment by sousabraga** [comment]
@jberns yes, you can assign this issue for me :) I cat start with it because this is my first contribution to an open source project.

**Comment by sousabraga** [comment]
Hi @jberns I create a first PR and if you agree I will replicate to the others models.
