### ISSUE TITLE
Endpoint naming convetion should be changed 

### ISSUE THREAD

**Issue by kaansonmezoz** [codefordenver/ideaLab#130]
- Kebab case is a standart for restul api endpoints.
   *  "In kebab case, all letters are written in lower case and the words are separated by a hyphen 
       or minus sign. Kebab Case or kebabCase becomes kebab-case."  
   *   E.g  /api/printjobs should be replaced by /api/print-jobs 

- Endpoints should be changed.
- Also controller tests should be fixed.
- Postman requests should be changed.

https://restfulapi.net/resource-naming/

**Comment by Will-Estes** [comment]
just merged a change for this in print jobs
