### ISSUE TITLE
Restrict backend create users to one per email

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#138]
Right now we can submit multiple post requests for the exact same email. We want the backend to reject it if the email already exists in the employee table

**Comment by codershin** [comment]
1) I can't see sample_dropbox.properties in the repository.
2) How can I request the latest dev resource file?

**Comment by sousabraga** [comment]
Hi, can I help you with this issue?

**Comment by codershin** [comment]
> Hi, can I help you with this issue?

Hi, I am trying to run this application locally, getting FileNotFoundException because the resource file "dropbox.properties" doesn't exist in the repository. It's mentioned in read.md that you need to request the dropbox.properties. Request to whom?

**Comment by sousabraga** [comment]
Hi @codershin, yes we need this file and it is not in the resource folder... @hannahkamundson can you send the latest dropbox dev resource file for us please?

**Comment by jberns** [comment]
Hi @sousabraga and @codershin.  I will take a look at what happened to that sample file and give you guys an update later today.

**Comment by jberns** [comment]
@sousabraga and @codershin Hi guys.  You can check out the readme on this branch for the details on the dropbox.properties file.  If you are not interacting with dropbox you just need to create a copy of the sample file and rename it leaving the contents as-is.  If you want to work on dropbox portions you will have to make your own access token. https://github.com/codefordenver/ideaLab/tree/update/dropbox-readme

**Comment by codershin** [comment]
> @sousabraga and @codershin Hi guys. You can check out the readme on this branch for the details on the dropbox.properties file. If you are not interacting with dropbox you just need to create a copy of the sample file and rename it leaving the contents as-is. If you want to work on dropbox portions you will have to make your own access token. https://github.com/codefordenver/ideaLab/tree/update/dropbox-readme

Thanks for the help @jberns! I was able to make this application run as sample_dropbox.properties is now there. But localhost:8080/greeting is giving WhiteLabel page. 
How do I run this project? So that I can test my changes.

**Comment by jberns** [comment]
Looks like we removed the hello world greeting page (If you want you can put in a pull request to remove that line).  If you have your docker container setup for the database you can try ```http://localhost:8080/api/print-jobs``` and it will return all of the test print jobs that where imported.  We have been using postman right now to hit most of the backend endpoints while another team is working on our frontend. 

 If you go into the ```ideaLab/Backend/src/main/java/idealab/api/controller/requests``` folder you can see what endpoints are currently available.

**Comment by sousabraga** [comment]
Hi @jberns, now I can run this app :) Can you assign this issue for me?

**Comment by sousabraga** [comment]
So I have a question, the entity Employee don't have a "email" field, what's field is unique? username?

**Comment by jberns** [comment]
> So I have a question, the entity Employee don't have a "email" field, what's field is unique? username?

Yes I think username should be unique for now.

As for issues depending on your skill level #129 is probably easy to start with to go through and update the tables if they don't have the created_at or updated_at fields.  You can skip the roles and status fields which are enumerations.

Ones that are a little bit harder could be #164 or #165.  Currently the new print operations were just making new records if they didn't already exist, but now that there is test data it can be validated against that.  If you are interested in either of those two I can write up more detailed acceptance criteria.

**Comment by sousabraga** [comment]
@jberns can you assign this issue for me?

**Comment by hannahkamundson** [comment]
@sousabraga assigned! Thanks for doing this. Closing it up. Let me know if you want to do any other issues!
