### ISSUE TITLE
Modify our exception handler to allow validation errors to be returned in response

### ISSUE THREAD

**Issue by divlogic** [codefordenver/ideaLab#151]
There was an exception handler added but it doesn't allow validation errors to come through in the response. 

I commented out the `@ControllerAdvice ` annotation to address it temporarily, but if we want that annotation we should allow validation errors through in order to get field specific messages.

**Comment by Will-Estes** [comment]
created branch validateRequests - Need to determine rules for all fields to provide specific error messages.

**Comment by Will-Estes** [comment]
May want to create issue for more specific error messaging. but my branch implemented a basic structure for requests.
