### ISSUE TITLE
PrintJobOperations | newPrintJob | Update database color lookup to only use enum values

### ISSUE THREAD

**Issue by jberns** [codefordenver/ideaLab#164]
Acceptance Criteria:
- [ ] Remove creating a new color if it does not exist (This was originally for testing only) and change to throwing error like the `findPrintJobById` example below.
```    
        if (databaseColor == null) {
            databaseColor = new ColorType(color); < Remove
            databaseColor = colorTypeRepo.save(databaseColor); <Remove
        }
```
- [ ] If `databaseColor == null` throw a new error named `COLOR_CANT_FIND_BY_TYPE`
- [ ] Add the new error the to the exception/ErrorType file as the next enumeration number with a `NOT FOUND` status
- [ ] Add test for color already existing in database - Test should return a print job without an error.
- [ ] Add test for color not existing in the database - Test should return the `COLOR_CANT_FIND_BY_TYPE` error.

Example of throwing an error:
```
       PrintJob printJob = printJobRepo.findPrintJobById(printId);
       if(printJob == null) {
            throw new IdeaLabApiException(PRINT_JOB_CANT_FIND_BY_ID);
        }
```

**Comment by sousabraga** [comment]
@jberns you can also assign this issue to me and write up more detailed acceptance criteria

**Comment by jberns** [comment]
@sousabraga yes, I will write some more detailed acceptance criteria over the weekend and you can work on this next week.

**Comment by sousabraga** [comment]
Nice @jberns, next week is good because I want to participate in Hacktober fest... So, I have a question, Can I create a branch from master? and the PR is to master too?

**Comment by jberns** [comment]
Yes, our master should be up to date and then you can PR your feature branch back into it.

**Comment by jberns** [comment]
hi @sousabraga . I updated the description with the issue requirements and added the hacktoberfest label if you were participating 👍

**Comment by sousabraga** [comment]
Hi @jberns. Thanks I will start. So, can you check the #129 issue and also add hacktoberfest label ?
