### ISSUE TITLE
Create Account page - DESIGN & Save Form Info

### ISSUE THREAD

**Issue by ethoreson** [codefordenver/ideaLab#169]
[Figma Design](https://www.figma.com/file/YkMHha03GCmYEg9HuXjknn/IdeaLAB?node-id=218%3A480)
- Still waiting for feedback from staff, so don't worry about matching designs to a tee
- Save form to state, this card can be considered DONE when the 'CREATE' button prints the user info to the console
- Please reach out to Emilie for questions

**Comment by JmMcGehee** [comment]
@ethoreson Is this issue still relevant?
