### ISSUE TITLE
Update documentation on docker compose

### ISSUE THREAD

**Issue by jberns** [codefordenver/ideaLab#177]
The project can now be run using ```docker-compose up``` to run all services.  Update the documentation to reflect this change.

**Comment by jatin69** [comment]
@jberns is this still open? I would like to take this up.

**Comment by jberns** [comment]
@jatin69 I don't think anyone is working on this currently, feel free to work on some documentation updates if you want to.

**Comment by divlogic** [comment]
Sorry, but I assigned it to myself a few days ago. I would probably pass on it because there are actually going to be a few notes that are os / project specific

**Comment by jatin69** [comment]
@divlogic Alright. As you say. Thanks for letting me know.
