### ISSUE TITLE
OA-06: Create user authentication for each get/post/etc request

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#18]
Create user authentication based on plan. This should be for each get/post/etc request.

**Comment by Will-Estes** [comment]
springSec branch. May need to discuss where the security is implemented, which roles, etc.

**Comment by kaansonmezoz** [comment]
This is can be done using Interceptors. We could use Spring Boot's HandlerInterceptor interface.

**Comment by Will-Estes** [comment]
Hi Kaan,
This was actually merged this passed Thursday. We decided on JWT. You should be able to see it in the master branch now (authentication is off except for DELETE requests). 
-Will

**Comment by kaansonmezoz** [comment]
Okay I'm going to check it out
