### ISSUE TITLE
Create a loading indicator

### ISSUE THREAD

**Issue by divlogic** [codefordenver/ideaLab#182]
- [x] There should be an indicator for any page that loads, that some kind of request is in progress. 
- [x] It should be applied cross the different pages in order to keep a uniform ui, unless there is some special reason to build a custom one for a specific request that gets made. 
- [x] queue page
- [x] mage users
- [x] upload

**Comment by Jashaul** [comment]
Hey!!, I would like to work on this issue

**Comment by Patrickcpoole** [comment]
Go for it!

**Comment by divlogic** [comment]
So right now, there's an existing loading indicator. I was thinking of this issue as kind of a general checklist thing so that each page uses the component, or maybe doing something with the context so that it displays automatically whenever the request service is performing those tasks. 

Might not actually be the best thing to start on if you aren't familiar with the project.

**Comment by Jashaul** [comment]
I will be able to do that. I would like to continue with this

**Comment by hannahkamundson** [comment]
This is completed via other pull requests
