### ISSUE TITLE
Plan the user authentication

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#19]
Figure out the design for user authentication & create a plan for it.

**Comment by hannahkamundson** [comment]
@Will-Estes assigned this to you because you've already done most of it. I can help with any further planning. Anything else need to be planned?

**Comment by Will-Estes** [comment]
@hannahkamundson I just need to know what a STAFF user can use vs. what a ADMIN user can use by controller endpoint.
