### ISSUE TITLE
Dropbox change path updates

### ISSUE THREAD

**Issue by Will-Estes** [codefordenver/ideaLab#203]
Look into whether this would be better than the current copy option: https://www.dropbox.com/developers/documentation/http/documentation#files-move
If so, make the update.

Ensure that the path passed ends with .stl for the file type

**Comment by piyushmor** [comment]
Hi! I can take this up. For ensuring the path ends with stl, does it mean that the path is always a file? also, does it mean that the new path should always be ending with .stl?

**Comment by jberns** [comment]
@piyushmor Yes we are only using files and no folders for this project.  So you can check if the last 4 characters of the string are an exact match to .stl, and if not you can add it on.

**Comment by divlogic** [comment]
Relates to: #148
