### ISSUE TITLE
AQ-04 DESIGN: Container/ overall queue

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#21]
Create the design for employee facing website. This should include:
-page that shows all tasks; this should be able to filter down by status (pending, in progress, completed); this should be able to allow the employee to change the status of a job and somehow submit their name so we can know what staff changed the status
-log in page
-change password page
-page to delete a print job
-page to edit a print job
-page to upload a CSV for mass quantity upload
-basic analysis page that lets them see basic analytics (# this month, # per month over time, favorite color, color by month, etc)

**Comment by ethoreson** [comment]
@anotherpatrickcollins and I are currently (08/14) working on designs in Figma & will link them here. please see either of us for any questions/ideas
