### ISSUE TITLE
GET request for all print jobs

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#31]
Create a GET request that returns all print jobs ever. This should return
-print job pk
-preferred color
-email address
-current status
-time current status occurred
-when was initially requested
-comments
-Dropbox link

**Comment by kaansonmezoz** [comment]
I'd like to contribute your project if it's possible :)

**Comment by kaansonmezoz** [comment]
https://github.com/codefordenver/ideaLab/pull/55

**Comment by Will-Estes** [comment]
merged to master

**Comment by hannahkamundson** [comment]
In process of updating operations

**Comment by divlogic** [comment]
Related PR:
https://github.com/codefordenver/ideaLab/pull/116
