### ISSUE TITLE
CSS: Queue page

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#327]
- [x] Add idealab logo (same size as Upload Page)
- [x] Add page title under logo 
Queue
- [x] Fix spacing of top nav items for readability
- [x] Fix alignment of email icon
- [ ] Fix scrollbar under save icon when state is changed in dropdown
- [x] Create bounding box for Color Picker
- [x] Color Picker moves other card content up instead of down
- [x] Cards don't seem to be updating unless it's back to the default state

**Comment by anotherpatrickcollins** [comment]
Upload Page logo styling
```
width: 50%;
margin: auto;
margin-top: 2rem;
border-style: none;
```

**Comment by anotherpatrickcollins** [comment]
Idea for navbar spacing:
- Not sure how to move the underline ::after over
- Add to .statusMenu li {};
`padding-right: 1rem;`
- Add to .statusMenu button {}
`padding-left: 1rem;`

**Comment by anotherpatrickcollins** [comment]
Idea for email icon alignment:
- .emailRecipient > svg {}
`margin-bottom: 4px;`

**Comment by anotherpatrickcollins** [comment]
Idea for scrollbar under save icon:
- .printAdditionalInfo {}
`overflow: overlay;`

**Comment by anotherpatrickcollins** [comment]
Idea for Color Picker bounding box:
- .colorPickerContainer {}
```
padding: .5rem;
background-color: #fff;
border-radius: 5px;
border: 1px solid rgba(169,169,169,1);
```

**Comment by ethoreson** [comment]
2 issues have been fixed on another branch & are now in master:
Create bounding box for Color Picker
 Color Picker moves other card content up instead of down
