### ISSUE TITLE
CSS: Create account page

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#331]
- [x] Make textboxes to match upload page
- [x] Make Create Account button to match Manage Accounts button
- [x] Change size of idealab logo to match Upload Page
- [x] Add page title under logo
	Create Account

**Comment by anotherpatrickcollins** [comment]
Textarea styling on upload page:
```
border: 2px solid black;
padding: 0.5rem;
margin-top: 1rem;
margin-bottom: 1rem;
margin-left: 0;
margin-right: 0;
```

Input styling on upload page:
```
width: 100%;
display: block;
height: 2em;
border-radius: 10px;
outline: none;
font-size: 1.5rem;
```

Manage Account button styling
```
background-color: #62a257;
border-radius: 6px;
color: #fff;
margin: 1em 0;
padding: 0.5em 2em;
font-size: 14px;
```

Upload Page logo styling
```
width: 50%;
margin: auto;
margin-top: 2rem;
border-style: none;
```
