### ISSUE TITLE
AQ-08: Ordering Logic for multi-prints from same user

### ISSUE THREAD

**Issue by ethoreson** [codefordenver/ideaLab#53]
IdeaLab has made the request that if the same person requests multiple print jobs in one day:
- First job is added to queue as normal.
- Any other jobs are pushed to bottom of queue. Any new requests coming in take priority over user's second print.
- Once first request is done, second print can start moving up in queue
- No more than 5 prints per 24 hours.

**Comment by ethoreson** [comment]
Note: We're receiving a ranking order w/ each print job. Backend will send a message when rejection is called for.

**Comment by hannahkamundson** [comment]
Done on backend
