### ISSUE TITLE
Change testing for PrintJobControllerTest

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#57]
This is generic. We need to update it to correctly test the PrintJobController

**Comment by GandalfTheJava** [comment]
I would love to have a go on this!

**Comment by aggarwal22ayush** [comment]
@hannahkamundson Can I take this up ? This is my first shot at an Open Source Project

**Comment by hannahkamundson** [comment]
@aggarwal22ayush Yes! Are you still interested?

**Comment by har-vy** [comment]
@hannahkamundson can you assign this issue to me if it is still open? I am a beginner in open source.

**Comment by piyushmor** [comment]
@hannahkamundson is this really an issue currently? can you highlight why you think this is too generic and does not test the class? I can actually pick it up if you think the current test is not enough

**Comment by hannahkamundson** [comment]
This has been updated
