### ISSUE TITLE
MU-02: Create a function to parse the CSV file

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#6]
DPL wants to be able to upload multiple print jobs at the same time. Once the CSV file has been designed, we need a function that can parse through the CSV

**Comment by Will-Estes** [comment]
Thinking this can be done on the frontend hitting the single endpoint. Putting on hold for now

**Comment by Will-Estes** [comment]
@hannahkamundson reached out to customer. We're going to do this on the front-end by calling the createNew endpoint multiple times.
