### ISSUE TITLE
ExceptionHandler should be implemented

### ISSUE THREAD

**Issue by kaansonmezoz** [codefordenver/ideaLab#71]
Exception handler will deal with all thrown but uncaught exceptions. It will also prepare a response for client. 

- ExceptionHandler should be implemented via @ControllerAdvice.
- Controllers should only pass response which will be gathered from service / business / operation classes. Instead of returning status as fail to the controller and checking in the controller (which brings extra logic to controller) in the service layer an exception should be thrown.
- Whenever an exception is handled by exceptionhandler, it should be logged.

**Comment by hannahkamundson** [comment]
@divlogic  Love that you added this! Helps keep us organized :)
Would you be able to select a milestone to add this to? That way I can keep track of what section it is in!
Thank you so much for contributing to the project!!

**Comment by Will-Estes** [comment]
This is implemented. Re-open if something is missing.
