### ISSUE TITLE
Add Color Picker to Queue Cards & Save Update

### ISSUE THREAD

**Issue by divlogic** [codefordenver/ideaLab#76]
See left queue wireframe for very rough example

I believe this is a good package for this (600k weekly downloads), but let me know if you don’t think it’s a good fit for this project: https://casesandberg.github.io/react-color/
These colors aren’t static: different locations will add or run out of colors. On the admin page they can update the ‘currently available colors’. For now, you can make some sort of temporary const tempColors = [‘red’, ‘blue’, ‘green’, ‘white’]; at the top of the file. (or save it in a file just like dummyData to keep things a little cleaner). 
This card will reach Done status when:

- [ ] Clicking a color will pop up a modal directly next to the color icon.
- [ ] When modal is open, clicking outside of modal will close.
- [ ] The modal will have circles representing the colors we’ve made in tempColors
- [ ] When you click one of these colors, save the updated color in PrintCardContainer’s state & change the display color to updated color.

**Comment by Patrickcpoole** [comment]
@divlogic I'm pretty sure this is done back when we were still branching based off everyone's name. Can you confirm this?
