### ISSUE TITLE
Create a table that stores email message info

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#90]
Create a table that has 2 columns: column for status enum and column for email message
- Create put request that lets you update the message (based on status that is given)
- Create get request that returns the message (based on status that is given)

This is for them to store the email message they want sent

**Comment by duyquangnguyenhac** [comment]
Hi, could I attempt this issue ?
James

**Comment by GandalfTheJava** [comment]
Is this completed yet? I would love to attempt otherwise

**Comment by sousabraga** [comment]
Hey @hannahkamundson, can I work on this?

**Comment by viditkumar** [comment]
Hey @hannahkamundson , is this issue still open? If yes, could you please assign this to me?
