### ISSUE TITLE
Create a PUT request that lets you modify email and email password

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/ideaLab#91]
The app will instantly email something out when marked complete. Create a put request that allows the email and password it is sent from to be changed
This info should be coming out of the general admin info table

- [x] Create frontend location to change the token
- [x] Create backend put request to change the token
- [x] Connect them

**Comment by sousabraga** [comment]
Hi @hannahkamundson @jberns can you explain a little bit more about this issue and assign for me?

**Comment by hannahkamundson** [comment]
@sousabraga thanks but we already finished it :) best of luck!
